Unable to revert mtime: /Library/Fonts
Exception in thread Thread-5 (UpdatePlanDisplay):
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Users/runner/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/runner/work/rfswarm/rfswarm/rfswarm_manager/rfswarm.py", line 4900, in UpdatePlanDisplay
    self.display_plan['lbl_sched_start_time'].set("")
  File "/Users/runner/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/tkinter/__init__.py", line 402, in set
    return self._tk.globalsetvar(self._name, value)
RuntimeError: main thread is not in main loop
