Exception in thread Thread-2:
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\a\rfswarm\rfswarm\rfswarm_manager\rfswarm.py", line 4900, in UpdatePlanDisplay
    self.display_plan['lbl_sched_start_time'].set("")
  File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\tkinter\__init__.py", line 377, in set
    return self._tk.globalsetvar(self._name, value)
RuntimeError: main thread is not in main loop
